### ISSUE TITLE
cannot add multiple roster name generator stages for the same actors

### ISSUE THREAD

**Issue by dirusulixes** [complexdatacollective/Architect#745]
Hi, I have a csv roster with a `name` column that I can use to generate a (small) roster name generator stage. However if I create a second roster name generator stage with a different prompt using the same csv file, the actors selected in the first stage appears already selected in the second one. 
I tried to duplicate and re-name the csv and I create separate node types for each of the stages. Even adding random names to one of the csv doesn't help. the names that match appear selected across multiple roster stages no matter what.

Am  I doing something wrong? I would like to show the same roster to respondents and ask them about fiendship, advice, etc. relations independently.

**Comment by jthrilly** [comment]
Hi @dirusulixes!

Thanks for reaching out, and sorry to hear about your issue.

The behaviour you are seeing is 'by design'. Our intention with the roster functionality is for nodes in a roster to be able to be "nominated" by the participant, at which point they are brought into the participant's interview network. They can then be analyzed further with subsequent stages. Once a node from a roster has been nominated, it is in the interview network, and will always appear as selected across all prompts and stages using the roster (as you saw).

Without knowing more, my suggestion is to use a broader name generator prompt on your initial roster stage, and then follow up with specific name interpreter stages for the attributes you are interested in, using nodes that were nominated in the roster stage. Hopefully that makes sense.

There is another more complex potential workaround. Interviewer matches nodes in a roster based on calculating a hash of the node and its attributes. You could theoretically create additional columns in your CSV corresponding to the stage you wish the node to be shown, and then create multiple nodes that are identical except for these attributes. These would then not be matched. You would also need to use the filtering functionality to filter the roster on each roster stage. This would of course be a lot of work, and would prevent you from using the non-roster interfaces to provide additional attribute data, so I cannot recommend it.

Please feel free to email us at info@networkcanvas.com to talk about this more. We are always happy to help.
