### ISSUE TITLE
Validation of unique node names in Quick Add Name Generator 

### ISSUE THREAD

**Issue by berniehogan** [complexdatacollective/Architect#784]
Presently node names can be assigned unique in a Node Form, which will highlight that the name is not unique. However, node names are not validated in the Quick Add control leading to the risk of creating a duplicate node name with no clear way to differentiate the two nodes subsequently. 

This is probably more enhancement than bug. But it does create clear data quality issues.

*Propose*: Node names get a validation box like any text area box. (I would still be in favour of the box being in the active state and on unique from the get go, but that is controversial since we don't enforce a default in that manner elsewhere). On the other hand, seeing a validation from the get go turned on might train people to be more comfortable with the behaviour. 

## Some knock on issues to consider:
- If uniqueness is a node property, it refers to the whole node pool. However, there are instances where not all existing nodes are visible. When the user adds a new node and is told 'Your answer must be unique' (which is what it says in the regular Text Input) we assume that the user understands this pool refers to all nodes. 
- In a Text control, when that warning appears the user can edit their answer. However, what about when a user drags a node in from a roster? This is in fact a bug in the current behavior. 
- Uniqueness by default could be a property in Architect, not interviewer, so it would not affect existing surveys. That is, if it detects a value for uniqueness in the schema, it uses it, if it is missing, I presume Interviewer would default to no validation. 
- Uniqueness and rosters:
  - There is the matter of actually validating a roster (which in theory could be done since the resource is pre-loaded). This behaviour would have to change with dynamically loaded resources. 
  - Should a mixed name generator and roster validate against _potential_ alters rather than realised ones? Right now, rosters and validation do not mix and that can create a problem.   
 - When a user drags a node into the bin form a roster it does not validate the name now as that is related to the field not the node.

**Comment by jthrilly** [comment]
> * If uniqueness is a node property, it refers to the whole node pool. However, there are instances where not all existing nodes are visible. When the user adds a new node and is told 'Your answer must be unique' (which is what it says in the regular Text Input) we assume that the user understands this pool refers to all nodes.

We can't do much about the way the field validation works in forms, as it has to be generalisable, but we can make sure the quick add messaging is more specific. Something like "A {nodeType} with the label '{label}' has already been added."

> * In a Text control, when that warning appears the user can edit their answer. However, what about when a user drags a node in from a roster? This is in fact a bug in the current behavior.

This is not something we can solve without a fairly significant refactor. The way validation works now is that it is a property of a form field - not of an entity attribute. We made this decision because we thought of validation as 'user facing'. 

Even if we made validation a property of entity attributes, I'm not sure what we could do about roster data. We can't refuse to add it, and we can't prompt the user to provide a different label (roster nodes are uniquely and repeatably identified by creating a hash of their attributes, so changing the label changes the hash).

Overall I think this is something researchers can manage fairly easily by ensuring (1) Roster node labels are unique, and (2) Roster nomination occurs before free-form alter elicitation.

**Comment by jthrilly** [comment]
Having reviewed the actual implementation, it turns out that validation is stored as a property of the variable - not the form field. This makes some of what I said above obsolete!

**Comment by jthrilly** [comment]
Implementation plan: 

- add the form field validation section to the quick add variable chooser in architect. It should set the validation property on the field as normal (or show it, if it is already set). 
- update the quick add input itself to use realtime input validation

**Comment by berniehogan** [comment]
I was thinking about the limits of our ability to validate on the roster screen for the reasons offered. I think that this point: 
> Overall I think this is something researchers can manage fairly easily by ensuring (1) Roster node labels are unique, and (2) Roster nomination occurs before free-form alter elicitation.

Is useful to retain as guidance in the documentation. I believe that it could be best featured under: https://documentation.networkcanvas.com/key-concepts/field-validation/
